(function(){
"use strict";
var Engine=Matter.Engine, World=Matter.World, Bodies=Matter.Bodies, Body=Matter.Body, Events=Matter.Events, Composite=Matter.Composite;

var CONFIG={
  GAME_MODE:"FREE", LOGICAL_W:720, LOGICAL_H:920,
  play:{left:34,right:686,top:0,bottom:916,dangerY:142,spawnY:58},
  autoDropMs:4000,spawnDelayMs:420,dangerHoldMs:2000,modeSeconds:180,
  physics:{gravity:1.05,restitution:.08,friction:.32,frictionAir:.012},
  direct:[{level:1,weight:.5},{level:2,weight:.3},{level:3,weight:.2}],seed:null
};
var PARKS=[
 {level:1,key:"geumjeongsan",short:"금정산",name:"금정산국립공원",image:"assets/characters/01_geumjeongsan_hq.webp",diameter:.085,color:"#c89558",area:66.136,score:10},
 {level:2,key:"gayasan",short:"가야산",name:"가야산국립공원",image:"assets/characters/02_gayasan_hq.webp",diameter:.108,color:"#d59655",area:76.792,score:30},
 {level:3,key:"juwangsan",short:"주왕산",name:"주왕산국립공원",image:"assets/characters/03_juwangsan_hq.webp",diameter:.135,color:"#9d7557",area:106.114,score:60},
 {level:4,key:"palgongsan",short:"팔공산",name:"팔공산국립공원",image:"assets/characters/04_palgongsan_hq.webp",diameter:.165,color:"#75523c",area:126.058,score:100},
 {level:5,key:"gyeongju",short:"경주",name:"경주국립공원",image:"assets/characters/05_gyeongju_hq.webp",diameter:.20,color:"#ce743f",area:136.550,score:150},
 {level:6,key:"jirisan",short:"지리산",name:"지리산국립공원",image:"assets/characters/06_jirisan_hq.webp",diameter:.242,color:"#293830",area:483.022,score:250},
 {level:7,key:"hallyeo",short:"한려해상",name:"한려해상국립공원",image:"assets/characters/07_hallyeohaesang_hq.webp",diameter:.285,color:"#267d87",area:537.479,score:500},
 {level:8,key:"eastern",short:"동부지역본부",name:"동부지역본부",image:"assets/characters/08_eastern.png",diameter:.32,color:"#b88b32",area:null,score:1000}
];
var stories=[["한국에서는 흔한 고라니, 세계에서는 귀한 동물?", "우리나라에서 자주 만나는 고라니는 세계적으로는 멸종 위험을 평가하는 IUCN 적색목록의 ‘취약종(VU)’으로 분류돼요.\n우리에게 흔하다고 지구 전체에도 흔한 건 아니랍니다!"], ["팔만대장경만 보물? 보관하는 건물도 세계유산!", "해인사의 장경판전은 팔만대장경을 보관하는 건물이에요. 바람길과 습도 조절을 고려한 건축 덕분에 나무로 된 경판을 오랫동안 보존해 왔어요.\n장경판전은 세계문화유산, 팔만대장경 등을 포함한 목판은 세계기록유산이에요. 보관된 기록도, 그것을 지킨 건물도 각각 유네스코 유산이랍니다!"], ["저 거대한 절벽이 화산재로 만들어졌다고?", "주왕산의 웅장한 절벽을 이루는 대표적인 암석은 ‘응회암’이에요. 아주 오래전 화산이 뿜어낸 화산재 등이 쌓이고 굳어 만들어졌죠.\n지금 걷는 조용한 계곡에 거대한 화산 활동의 흔적이 남아 있는 거예요!"], ["갓바위는 바위 이름인 줄 알았는데, 불상이었네?", "팔공산의 ‘갓바위’는 머리에 갓처럼 생긴 넓적한 돌을 얹은 불상을 부르는 이름이에요.\n정식 이름은 ‘경산 팔공산 관봉 석조여래좌상’이에요. 갓을 쓴 듯한 모습 때문에 붙은 별명이 더 유명해진 거죠!"], ["석굴암은 동굴을 파서 만든 게 아니에요!", "석굴암은 자연 동굴 안에 불상을 넣은 곳이 아니에요. 단단한 화강암을 다듬어 쌓아 올린 인공 석굴이랍니다.\n둥근 천장까지 돌로 만든 신라인들의 설계와 건축 기술이 숨어 있어요."], ["곰의 밥상에는 꿀보다 숲의 열매가 자주 올라요!", "반달가슴곰은 꿀도 좋아하지만, 평소에는 도토리와 여러 산열매 같은 식물성 먹이를 많이 먹어요.\n계절에 따라 먹이가 달라지고 곤충도 먹는 잡식동물이죠. 꿀단지보다 풍성한 숲이 곰에게 더 중요한 셈이에요!"], ["상괭이를 그릴 때는 등지느러미를 빼주세요!", "고래를 그리면 등에 삼각형 지느러미부터 그리곤 하죠? 하지만 상괭이에게는 그런 등지느러미가 없어요.\n웃는 듯한 얼굴과 매끈한 등이 상괭이를 알아보는 힌트랍니다!\n상괭이는 폐로 숨 쉬는 해양보호생물이에요. 그물에 뜻하지 않게 함께 잡히는 ‘혼획’을 줄여야 안전하게 숨 쉬러 올라올 수 있어요."], ["3월 3일은 지리산이 국립공원이 된 날일까요?", "아니에요! 3월 3일은 국립공원 제도의 바탕이 된 「공원법」이 1967년에 제정된 날이에요.\n이 날짜의 의미를 담아 ‘국립공원의 날’로 기념하고 있어요. 멋진 자연을 함께 지키기로 한 약속을 기억하는 날인 셈이죠!\n오늘 알게 된 이야기 하나, 다른 사람에게도 들려주세요!"]];
PARKS.forEach(function(p,i){p.headline=stories[i][0];p.description=stories[i][1]});
var $=function(s){return document.querySelector(s)}, canvas=$("#gameCanvas"),ctx=canvas.getContext("2d"),nextCanvas=$("#nextCanvas"),nctx=nextCanvas.getContext("2d");
var ui={score:$("#score"),timeBox:$("#timeBox"),time:$("#time"),toast:$("#toast"),start:$("#startOverlay"),end:$("#endOverlay"),endLabel:$("#endLabel"),endTitle:$("#endTitle"),finalScore:$("#finalScore"),highest:$("#highestPark"),progress:$("#progress"),sound:$("#soundBtn")};
var images={},engine=null,world=null,raf=0,state="START",generation=0,bodies=[],particles=[],mergeQueue=[],uid=1,score=0,highest=0,currentLevel=1,nextLevel=1,pending=null,pendingAt=0,nextSpawnAt=0,dangerSince=null,startedAt=0,lastNow=0,physicsAccumulator=0,muted=false,audioCtx=null,rng=Math.random,pointer=null,toastTimer=0,finalAchieved=false,visuals=window.ParkVisuals;
var acquired=new Set(),pausedAt=null,pausedTotal=0,resumeTimer=0,returnFocus=null;
function gameNow(){return (pausedAt===null?performance.now():pausedAt)-pausedTotal}

function park(level){return PARKS[level-1]} function radius(level){return CONFIG.LOGICAL_W*park(level).diameter/2}
function seeded(seed){return function(){seed|=0;seed=seed+0x6D2B79F5|0;var t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function drawLevel(){var x=rng(),sum=0;for(var i=0;i<CONFIG.direct.length;i++){sum+=CONFIG.direct[i].weight;if(x<sum)return CONFIG.direct[i].level}return 3}
function loadImages(){PARKS.forEach(function(p){var im=new Image();images[p.level]=im;im.onload=im.onerror=function(){drawNext();drawProgressImages();drawResult();if(state==="START")render(0)};im.src=p.image})}
function buildProgress(){ui.progress.innerHTML="";PARKS.forEach(function(p){var d=document.createElement("button");d.type="button";d.className="step";d.dataset.level=p.level;d.innerHTML='<canvas width="88" height="88" aria-hidden="true"></canvas><i>'+p.level+'</i><span>'+p.short+'</span>';d.addEventListener("click",function(){openInfo(p.level)});ui.progress.appendChild(d)});updateProgress();drawProgressImages()}
function drawProgressImages(){document.querySelectorAll(".step").forEach(function(x){var c=x.querySelector("canvas"),cx=c.getContext("2d");cx.clearRect(0,0,88,88);drawPark(cx,+x.dataset.level,44,43,74,0,1)})}
function updateProgress(){document.querySelectorAll(".step").forEach(function(x){var level=+x.dataset.level,on=acquired.has(level);if(on&&!x.classList.contains("on")&&state==="PLAYING"){x.classList.add("newly-unlocked")}x.classList.toggle("on",on);x.classList.toggle("current",level===highest);x.disabled=!on;x.setAttribute("aria-label",level+"단계 "+park(level).name+(on?" 정보 보기":" 미달성"))});var count=$("#collectionCount");if(count)count.textContent=acquired.size+" / 8"}
function audio(){if(muted)return null;if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume();return audioCtx}
function tone(freq,dur,type,vol,delay){var a=audio();if(!a)return;var o=a.createOscillator(),g=a.createGain(),t=a.currentTime+(delay||0);o.type=type||"sine";o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(vol||.035,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(a.destination);o.start(t);o.stop(t+dur)}
function sound(kind,level){if(kind==="drop")tone(240,.07,"sine",.025);else if(kind==="merge"){tone(420+level*35,.12,"sine",.035);tone(630+level*30,.14,"sine",.025,.045)}else if(kind==="win"){tone(523,.18,"sine",.04);tone(659,.18,"sine",.04,.14);tone(784,.28,"sine",.04,.28)}else if(kind==="over"){tone(330,.22,"triangle",.03);tone(220,.3,"triangle",.03,.18)}}
function cleanup(){infoFromResult=false;generation++;if(raf)cancelAnimationFrame(raf);raf=0;clearTimeout(resumeTimer);resumeTimer=0;pausedAt=null;pausedTotal=0;var info=$("#infoOverlay");if(info)info.classList.remove("active");document.body.classList.remove("game-paused");if(engine){Events.off(engine);Composite.clear(world,false,true);Engine.clear(engine)}engine=null;world=null;bodies=[];particles=[];mergeQueue=[];pending=null;pointer=null;dangerSince=null;clearTimeout(toastTimer);ui.toast.className="toast";ui.toast.textContent="";visuals.clear()}
function initWorld(){engine=Engine.create();world=engine.world;engine.gravity.y=CONFIG.physics.gravity;var p=CONFIG.play,wall={isStatic:true,restitution:0,friction:.4,render:{visible:false}};World.add(world,[Bodies.rectangle(p.left-18,CONFIG.LOGICAL_H/2,36,CONFIG.LOGICAL_H,wall),Bodies.rectangle(p.right+18,CONFIG.LOGICAL_H/2,36,CONFIG.LOGICAL_H,wall),Bodies.rectangle(CONFIG.LOGICAL_W/2,p.bottom+18,p.right-p.left+72,36,wall)]);Events.on(engine,"collisionStart",onCollision);Events.on(engine,"afterUpdate",afterUpdate)}
function makeBody(level,x,y,settled){var r=radius(level),b=Bodies.circle(x,y,r,{restitution:CONFIG.physics.restitution,friction:CONFIG.physics.friction,frictionAir:CONFIG.physics.frictionAir,density:.0016});Body.setInertia(b,Infinity);b.plugin.park={level:level,uid:uid++,mergeLocked:false,safe:!!settled,landed:!!settled,dangerAt:null,visualAngle:0,popUntil:gameNow()+240,generation:generation};bodies.push(b);World.add(world,b);acquired.add(level);highest=Math.max(highest,level);updateProgress();return b}
function spawnPending(now){if(state!=="PLAYING"||pending)return;pending={level:currentLevel,x:CONFIG.LOGICAL_W/2};pendingAt=now;drawNext()}
function drop(){if(state!=="PLAYING"||!pending)return false;var q=pending;pending=null;var b=makeBody(q.level,q.x,CONFIG.play.spawnY,false);Body.setVelocity(b,{x:0,y:.6});sound("drop");currentLevel=nextLevel;nextLevel=drawLevel();nextSpawnAt=gameNow()+CONFIG.spawnDelayMs;drawNext();return true}
function onCollision(ev){if(state!=="PLAYING")return;ev.pairs.forEach(function(pair){var a=pair.bodyA.plugin.park,b=pair.bodyB.plugin.park;if(a)a.landed=true;if(b)b.landed=true;if(!a||!b||a.level>=8||a.level!==b.level||a.mergeLocked||b.mergeLocked)return;a.mergeLocked=b.mergeLocked=true;mergeQueue.push({a:pair.bodyA,b:pair.bodyB,level:a.level})})}
function exists(b){return Composite.get(world,b.id,"body")===b}
function afterUpdate(){
  if(!mergeQueue.length||state!=="PLAYING")return;
  var q=mergeQueue.splice(0);q.sort(function(x,y){return x.a.id-y.a.id});
  q.forEach(function(m){
    if(state!=="PLAYING"||!exists(m.a)||!exists(m.b))return;
    removeBody(m.a);removeBody(m.b);
    var x=(m.a.position.x+m.b.position.x)/2,y=(m.a.position.y+m.b.position.y)/2,p=park(m.level);
    score+=p.score;updateScore();
    visuals.merge(x,y,Math.min(8,m.level+1),p.score,m.level===7,gameNow());
    if(m.level===7){makeBody(8,x,y,true);finalAchieved=true;finish("SUCCESS");return}
    var n=makeBody(m.level+1,x,y,true),vx=(m.a.velocity.x+m.b.velocity.x)*.18,vy=(m.a.velocity.y+m.b.velocity.y)*.18;
    Body.setVelocity(n,{x:vx,y:vy});
    var created=park(m.level+1),firstFinal=created.level===7;
    showToast(firstFinal?"한려해상국립공원 완성!":created.name+"!",firstFinal?"special":"",firstFinal?1500:800,firstFinal?"한 번 더 합쳐 동부권역을 완성하세요!":"새로운 도장 발견 · +"+p.score);
    sound(firstFinal?"win":"merge",created.level);
  });
}
function removeBody(b){World.remove(world,b);var i=bodies.indexOf(b);if(i>=0)bodies.splice(i,1)}
function burst(x,y,level){var colors=[park(Math.min(level,7)).color,"#f5cf68","#fff"];for(var i=0;i<10+level*2;i++)particles.push({x:x,y:y,vx:(Math.random()-.5)*(2+level*.2),vy:(Math.random()-.8)*(2+level*.2),life:500+Math.random()*350,color:colors[i%3],size:2+Math.random()*4})}
function updateScore(){ui.score.textContent=score.toLocaleString("ko-KR")}
function showToast(text,cls,dur,detail){ui.toast.textContent="";var title=document.createElement("strong"),sub=document.createElement("span");title.textContent=text;sub.textContent=detail||"";ui.toast.appendChild(title);ui.toast.appendChild(sub);ui.toast.className="toast "+(cls||"");ui.toast.style.setProperty("--toast-duration",(dur||900)+"ms");void ui.toast.offsetWidth;ui.toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(function(){ui.toast.className="toast"},dur||900)}
function start(){cleanup();state="PLAYING";score=0;highest=0;acquired.clear();finalAchieved=false;uid=1;physicsAccumulator=0;rng=CONFIG.seed===null?Math.random:seeded(CONFIG.seed);currentLevel=drawLevel();nextLevel=drawLevel();nextSpawnAt=0;startedAt=gameNow();lastNow=startedAt;updateScore();buildProgress();initWorld();ui.start.classList.remove("active");ui.end.classList.remove("active");ui.timeBox.classList.toggle("hidden",CONFIG.GAME_MODE!=="180SEC");spawnPending(startedAt);raf=requestAnimationFrame(loop);audio()}
function drawResult(){var c=$("#resultCanvas");if(!c)return;var cx=c.getContext("2d");cx.clearRect(0,0,c.width,c.height);if(highest)drawPark(cx,highest,c.width/2,c.height/2,c.width*.88,0,1)}
function finish(reason){if(state!=="PLAYING")return;state=reason;var success=reason==="SUCCESS";sound(success?"win":"over");pending=null;pointer=null;ui.endLabel.textContent=success?"ALL PARKS DISCOVERED":reason==="TIME_OVER"?"TIME OVER":"EXPLORE AGAIN";ui.endTitle.textContent=success?"동부권역 완성!":"탐방을 마쳤어요";ui.finalScore.textContent=score.toLocaleString("ko-KR");ui.highest.textContent=highest?highest+"단계 · "+park(highest).short:"아직 발견한 공원이 없어요";var message=$("#resultMessage");if(message)message.textContent=success?"일곱 공원이 함께하는 동부권역을 완성했어요!":"도장 "+acquired.size+"개를 발견했어요. 다음 탐방에도 함께해요!";drawResult();var stamps=$("#resultStamps");if(stamps){stamps.textContent="";PARKS.forEach(function(p){var s=document.createElement("span");s.className=acquired.has(p.level)?"earned":"";s.textContent=p.short;stamps.appendChild(s)})}$("#finalStoryBtn").hidden=!success;ui.end.classList.toggle("success",success);ui.end.classList.add("active");$("#retryBtn").focus()}
function restart(){cleanup();state="START";score=0;highest=0;acquired.clear();finalAchieved=false;physicsAccumulator=0;currentLevel=nextLevel=1;updateScore();buildProgress();drawNext();drawResult();ui.end.classList.remove("active","success");ui.start.classList.add("active");render(0);$("#startBtn").focus()}
function pause(){if(state!=="PLAYING")return false;pausedAt=performance.now();state="PAUSED";pointer=null;clearTimeout(toastTimer);ui.toast.classList.remove("show");document.body.classList.add("game-paused");return true}
var infoFromResult=false;
function openInfo(level){if(!acquired.has(level))return false;var ended=state==="SUCCESS"||state==="GAME_OVER"||state==="TIME_OVER";if(!ended&&!pause())return false;infoFromResult=ended;var overlay=$("#infoOverlay");if(!overlay){resume();return false}returnFocus=document.activeElement;$("#infoTitle").textContent=park(level).name;$("#infoHeadline").textContent=park(level).headline;$("#infoClose").textContent=infoFromResult?"완료 화면으로":"게임 계속하기 ▶";$("#infoHint").textContent=infoFromResult?"창 바깥을 터치하면 완료 화면으로 돌아가요":"창 바깥을 터치하면 1초 뒤 게임이 이어져요";$("#infoDescription").textContent=park(level).description;$("#infoImage").src=park(level).image;$("#infoImage").alt=park(level).name+" 캐릭터";$("#infoImage").hidden=false;overlay.classList.add("active");$("#infoClose").focus();return true}
function showPause(){if(!pause())return;infoFromResult=false;$("#infoHeadline").textContent="";$("#infoClose").textContent="게임 계속하기 ▶";$("#infoHint").textContent="창 바깥을 터치하면 1초 뒤 게임이 이어져요";returnFocus=document.activeElement;$("#infoTitle").textContent="잠시 쉬어가요";$("#infoDescription").textContent="게임이 일시정지되었어요. 준비되면 계속하기를 눌러 주세요.";$("#infoImage").hidden=true;$("#infoOverlay").classList.add("active");$("#infoClose").focus()}
function resume(){if(infoFromResult){infoFromResult=false;$("#infoOverlay").classList.remove("active");if(returnFocus&&returnFocus.isConnected)returnFocus.focus();returnFocus=null;return true}if(state!=="PAUSED")return false;var overlay=$("#infoOverlay");if(overlay)overlay.classList.remove("active");state="RESUMING";showToast("잠시 후 계속해요","",1000,"1초 후 탐방을 이어갑니다");resumeTimer=setTimeout(function(){if(state!=="RESUMING")return;pausedTotal+=performance.now()-pausedAt;pausedAt=null;lastNow=gameNow();state="PLAYING";document.body.classList.remove("game-paused");if(returnFocus&&returnFocus.isConnected)returnFocus.focus();returnFocus=null;if(document.hidden)showPause()},1000);return true}
function update(now,dt){if(state!=="PLAYING")return;if(!pending&&now>=nextSpawnAt)spawnPending(now);if(pending&&now-pendingAt>=CONFIG.autoDropMs)drop();var dangerTimes=[];bodies.forEach(function(b){var d=b.plugin.park;if(!d.safe&&b.bounds.min.y>CONFIG.play.dangerY+4)d.safe=true;d.visualAngle+=(Math.max(-.262,Math.min(.262,b.velocity.x*.025))-d.visualAngle)*.12;var above=(d.safe||d.landed)&&b.bounds.min.y<CONFIG.play.dangerY;if(above){if(d.dangerAt===null)d.dangerAt=now;dangerTimes.push(d.dangerAt)}else d.dangerAt=null});dangerSince=dangerTimes.length?Math.min.apply(Math,dangerTimes):null;if(dangerTimes.some(function(t){return now-t>=CONFIG.dangerHoldMs}))finish("GAME_OVER");if(CONFIG.GAME_MODE==="180SEC"){var left=Math.max(0,CONFIG.modeSeconds-(now-startedAt)/1000),whole=Math.ceil(left);ui.time.textContent=String(Math.floor(whole/60)).padStart(2,"0")+":"+String(whole%60).padStart(2,"0");if(left<=0)finish("TIME_OVER")}particles.forEach(function(p){p.x+=p.vx*dt/16;p.y+=p.vy*dt/16;p.vy+=.035*dt/16;p.life-=dt});particles=particles.filter(function(p){return p.life>0})}
function loop(){var now=gameNow(),step=1000/60,dt=Math.min(50,now-lastNow||step);lastNow=now;if(state==="PLAYING"){physicsAccumulator=Math.min(50,physicsAccumulator+dt);while(physicsAccumulator>=step&&state==="PLAYING"){Engine.update(engine,step);physicsAccumulator-=step}update(now,dt)}if(state!=="PAUSED"&&state!=="RESUMING")render(now);if(state==="PLAYING"||state==="PAUSED"||state==="RESUMING")raf=requestAnimationFrame(loop);else raf=0}
function coverImage(c,im,x,y,size,angle){c.save();c.translate(x,y);c.rotate(angle||0);c.beginPath();c.arc(0,0,size/2-2,0,Math.PI*2);c.clip();var ratio=im.naturalWidth/im.naturalHeight,w=size,h=size;if(ratio>1)w=size*ratio;else h=size/ratio;c.drawImage(im,-w/2,-h/2,w,h);c.restore()}
function fallback(c,p,x,y,size){c.save();c.translate(x,y);c.beginPath();c.arc(0,0,size/2,0,Math.PI*2);c.fillStyle=p.color;c.fill();c.strokeStyle="#fff";c.lineWidth=Math.max(3,size*.045);c.stroke();c.fillStyle="#fff";c.textAlign="center";c.font="bold "+Math.max(12,size*.22)+"px Malgun Gothic";c.fillText(p.level+"단계",0,-2);c.font="bold "+Math.max(10,size*.16)+"px Malgun Gothic";c.fillText(p.short,0,size*.22);c.restore()}
function drawPark(c,level,x,y,size,angle,pop){visuals.drawPark(c,park(level),images[level],x,y,size,angle,pop)}
function drawNext(){nctx.clearRect(0,0,nextCanvas.width,nextCanvas.height);var lv=pending?nextLevel:currentLevel;drawPark(nctx,lv,46,46,76,0,1);var name=$("#nextName");if(name)name.textContent=park(lv).short;nextCanvas.setAttribute("aria-label","다음 "+park(lv).name)}
function render(now){
  ctx.clearRect(0,0,canvas.width,canvas.height);
  var p=CONFIG.play;visuals.background(ctx,canvas.width,canvas.height,p,now,dangerSince!==null);
  visuals.drawEffects(ctx,now,false,canvas.width,canvas.height);
  bodies.forEach(function(b){var d=b.plugin.park,pop=!visuals.reduced&&now<d.popUntil?1+.2*Math.sin((d.popUntil-now)/240*Math.PI):1;drawPark(ctx,d.level,b.position.x,b.position.y,radius(d.level)*2,d.visualAngle,pop)});
  if(pending){var hint=!visuals.reduced&&now-pendingAt>CONFIG.autoDropMs-420?Math.sin(now/45)*2:0;drawPark(ctx,pending.level,pending.x,p.spawnY+hint,radius(pending.level)*2,0,1)}
  visuals.drawEffects(ctx,now,true,canvas.width,canvas.height);
}
function logicalX(clientX){var r=canvas.getBoundingClientRect();return Math.max(CONFIG.play.left+radius(pending?pending.level:1),Math.min(CONFIG.play.right-radius(pending?pending.level:1),(clientX-r.left)*canvas.width/r.width))}
canvas.tabIndex=0;
canvas.addEventListener("pointerdown",function(e){if(state!=="PLAYING"||!pending)return;e.preventDefault();canvas.focus();canvas.setPointerCapture(e.pointerId);pointer={id:e.pointerId,x:e.clientX,y:e.clientY,t:performance.now(),moved:0};pending.x=logicalX(e.clientX)});
canvas.addEventListener("pointermove",function(e){if(state!=="PLAYING"||!pending)return;if(e.pointerType==="mouse"&&!pointer){pending.x=logicalX(e.clientX);return}if(!pointer||pointer.id!==e.pointerId)return;e.preventDefault();pointer.moved=Math.max(pointer.moved,Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y));pending.x=logicalX(e.clientX)});
canvas.addEventListener("pointerup",function(e){if(!pointer||pointer.id!==e.pointerId)return;e.preventDefault();var tap=pointer.moved<10&&performance.now()-pointer.t<350;pointer=null;if(tap)drop()});canvas.addEventListener("pointercancel",function(){pointer=null});
document.addEventListener("keydown",function(e){if($("#infoOverlay").classList.contains("active")){if(e.key==="Escape"){e.preventDefault();resume()}else if(e.key==="Tab"){e.preventDefault();$("#infoClose").focus()}return}if(state!=="PLAYING"||e.target.closest("button,input,select,textarea,a,[role=dialog]"))return;if((e.key==="ArrowLeft"||e.key==="ArrowRight")&&pending){e.preventDefault();var step=e.shiftKey?22:11,p=park(pending.level),r=radius(p.level);pending.x=Math.max(CONFIG.play.left+r,Math.min(CONFIG.play.right-r,pending.x+(e.key==="ArrowLeft"?-step:step)))}else if((e.code==="Space"||e.key===" ")&&!e.repeat){e.preventDefault();drop()}else if(e.key.toLowerCase()==="r"){e.preventDefault();restart()}});
$("#startBtn").addEventListener("click",start);$("#retryBtn").addEventListener("click",restart);$("#restartBtn").addEventListener("click",restart);if($("#homeBtn"))$("#homeBtn").addEventListener("click",restart);if($("#infoClose"))$("#infoClose").addEventListener("click",resume);if($("#pauseBtn"))$("#pauseBtn").addEventListener("click",showPause);ui.sound.addEventListener("click",function(){muted=!muted;ui.sound.textContent=muted?"🔇 소리":"🔊 소리";ui.sound.setAttribute("aria-label",muted?"소리 켜기":"소리 끄기");if(!muted)audio()});
$("#finalStoryBtn").addEventListener("click",function(){openInfo(8)});
var backdropPointer=null;
$("#infoOverlay").addEventListener("pointerdown",function(e){backdropPointer=e.target===this?e.pointerId:null});
$("#infoOverlay").addEventListener("click",function(e){if(e.target===this&&backdropPointer!==null){e.preventDefault();e.stopPropagation();backdropPointer=null;resume()}});
$("#infoOverlay").addEventListener("pointercancel",function(){backdropPointer=null});
document.addEventListener("visibilitychange",function(){if(document.hidden&&state==="PLAYING")showPause()});
function fitScreen(){var scale=Math.min(Math.max(1,window.innerWidth-16)/1440,Math.max(1,window.innerHeight-16)/900),v=$("#viewport");$("#app").style.transform="scale("+scale+")";v.style.width=1440*scale+"px";v.style.height=900*scale+"px"}
window.addEventListener("resize",fitScreen);fitScreen();loadImages();buildProgress();drawNext();render(0);
window.__NP_GAME__={CONFIG:CONFIG,PARKS:PARKS,start:start,restart:restart,home:restart,pause:pause,resume:resume,openInfo:openInfo,finish:finish,drop:drop,drawLevels:function(n){var out=[];while(n-->0)out.push(drawLevel());return out},forceSpawn:function(level,x,y){if(!park(level))throw new Error("Invalid park level");if(state!=="PLAYING")start();return makeBody(level,x===undefined?360:x,y===undefined?300:y,true)},snapshot:function(){var now=gameNow();return{state:state,score:score,highest:highest,acquired:Array.from(acquired),current:currentLevel,next:nextLevel,pending:pending&&pending.level,autoDropRemaining:pending?Math.max(0,CONFIG.autoDropMs-(now-pendingAt)):null,spawnRemaining:pending?null:Math.max(0,nextSpawnAt-now),modeRemaining:Math.max(0,CONFIG.modeSeconds*1000-(now-startedAt)),dangerRemaining:dangerSince===null?null:Math.max(0,CONFIG.dangerHoldMs-(now-dangerSince)),dynamicBodies:bodies.map(function(b){return{level:b.plugin.park.level,x:b.position.x,y:b.position.y,locked:b.plugin.park.mergeLocked}})}}};
})();
